force-app/main/default/objects/Product2/fields/Award_Image_ID__c.field-meta.xml
<CustomField>
    <fullName>Award_Image_ID__c</fullName>
    <label>Award Image ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Product2Controller.cls
public without sharing class Product2Controller {

    @AuraEnabled(cacheable=true)
    public static List<Product2> getProductsByCode(
        String productcode,
        String  productcode2,
        String productcode3,
        String productcode4
    ) {
        try {

            List<String> productCodes = new List<String>{};
            if (productcode != null) {
                productCodes.add(productcode);
            }
            if (productcode2 != null) {
                productCodes.add(productcode2);
            }
            if (productcode3 != null) {
                productCodes.add(productcode3);
            }
            if (productcode4 != null) {
                productCodes.add(productcode4);
            }
            List<Product2> products = [SELECT Id, Name, ProductCode, Description, Content_Type__c, Award_Image_ID__c FROM Product2 WHERE ProductCode IN :productCodes];

            return products;
        } catch (Exception e) {
            System.debug('Error in apex class: ' + e.getMessage() + ' ' + e.getLineNumber() + ' ' + e.getCause());
            System.debug('Stack trace: ' + e.getStackTraceString());
            throw e;
        }
    }
}